version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo_hotel
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend_hotel
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/hotel
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend_hotel
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app

volumes:
  mongo_data: